version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: subrosa
      POSTGRES_USER: subrosa_user
      POSTGRES_PASSWORD: secret
  web:
    build: .
    environment:
      PGHOST: db
    links:
      - "db"
    ports:
      - "80:8000"
    depends_on:
      - db
 
